# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
